server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://rm-wz9v8xc42t1go7ptc0o.mysql.rds.aliyuncs.com:3306/yaofan
    username: root
    password: 112233ccddEE
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    name: logging:logs/application-yaofan.log