server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://rm-wz9v8xc42t1go7ptc0o.mysql.rds.aliyuncs.com:3306/yaofan?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 112233ccddEE
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  file:
    name: logging:logs/application-yaofan.log
wechat:
  appid: "wxaaceff5dd77419f7"
  secret: "9da02665a9c331b74cb170fba60ea5fd"
  user_url: "https://api.weixin.qq.com/sns/jscode2session"

cbs:
  imagesPath: C:/smartYou/img/
domain:
  name: https://www.wegou1688.com:6060